/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import monitorModel from './monitorf.glb';
import OnlyMonitor from './OnlyMonitor';
import Mac from './Mac';

export default function Monitor(props) {
  return (
    <group {...props} dispose={null}>
      <OnlyMonitor />
      <Mac />
    </group>
  );
}
