/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import macModel from './mac_0215.glb';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(macModel);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mac2.geometry}
        material={nodes.mac2.material}
        position={[-0.46, -0.33, 1.75]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mac2001.geometry}
        material={nodes.mac2001.material}
        position={[-0.48, -0.29, 1.75]}
        rotation={[-Math.PI, 0, -2.26]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve001.geometry}
        material={materials['SVGMat.001']}
        position={[-0.48, -0.26, 1.75]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.28}
      />
    </group>
  );
}

useGLTF.preload(macModel);
