/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import monitorModel from './monitorf.glb';

export default function Monitor(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(monitorModel);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stand.geometry}
        material={nodes.stand.material}
        position={[-0.27, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-0.47, 0.63, -0.01]}
        rotation={[0, 0, -Math.PI / 2]}
      />
    </group>
  );
}

useGLTF.preload(monitorModel);
