/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import careerModels from './careers.glb';
import snuModel from './snu.glb';
import loadcompleteModel from './loadcomplete.glb';
import springcampModel from './springcamp.glb';
import { useLoader } from '@react-three/fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(careerModels);

  const loadcomplete = useLoader(GLTFLoader, loadcompleteModel);
  const snu = useLoader(GLTFLoader, snuModel);
  const springcamp = useLoader(GLTFLoader, springcampModel);
  return (
    <group {...props}>
      <primitive object={loadcomplete.scene} scale={0.5} position={[0, 0, 3]} />
      <primitive object={snu.scene} scale={0.5} position={[1, 0, 3]} />
      <primitive object={springcamp.scene} position={[3, -3.6, 0]} />
    </group>
  );
}

useGLTF.preload(careerModels);
