/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three';
import React, { useRef } from 'react';
import catModel from './cat.glb';
import catModelf from './catf.fbx';
import catTexture from './cattexture.png';
import {
  useFBX,
  useGLTF,
  PresentationControls,
  useTexture,
} from '@react-three/drei';
export default function Cat(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(catModel);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[1.96, 3.45, -0.31]}
        rotation={[2.76, 0.67, -0.5]}
        scale={[0.07, 0.3, 0.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[1.88, 3.64, -1.06]}
        rotation={[2.26, 0.72, -0.54]}
        scale={[0.07, 0.3, 0.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[2.02, 3.47, -0.35]}
        rotation={[2.67, 0.64, -0.48]}
        scale={[0.05, 0.22, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[1.95, 3.64, -1.01]}
        rotation={[2.38, 0.65, -0.54]}
        scale={[0.05, 0.22, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[2.05, 3.51, -0.42]}
        rotation={[2.52, 0.63, -0.46]}
        scale={[0.03, 0.12, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere005.geometry}
        material={nodes.Sphere005.material}
        position={[1.99, 3.65, -0.94]}
        rotation={[2.43, 0.68, -0.46]}
        scale={[0.03, 0.12, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mball011.geometry}
        material={materials['Material.001']}
        position={[0, 1.12, -0.93]}
        rotation={[-0.02, -0.13, -0.01]}
        scale={[0.84, 0.92, 1.05]}
      />
    </group>
  );
}

useGLTF.preload(catModel);
